apiVersion: v1
kind: Service
metadata:
  name: gradio-app-service
  labels:
    app: gradio-app
spec:
  selector:
    app: gradio-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7861
